package org.an.model;

public interface EAuctionConstants {
	   int INVALID_REQUEST=400;

       int INVALID_SERVER_REQUEST=500;

       int SUCCESS=200;

       String PRODUCT_CREATED="PRODUCT CREATED";

       String PRODUCT_NOT_CREATED="PRODUCT NOT CREATED";

       String PRODUCT_RETRIEVED="PRODUCT RETRIEVED";

       String SELLER_PRODUCT_RETRIEVED="SELLER PRODUCT RETRIEVED";

       String SELLER_PRODUCT_NOT_RETRIEVED="SELLER PRODUCT NOT RETRIEVED";

       String PRODUCT_NOT_RETRIEVED="PRODUCT NOT RETRIEVED";

       String PRODUCT_DELETED="PRODUCT DELETED";

       String PRODUCT_BIDS_NOT_RETRIEVED="PRODUCT BIDS NOT EXIST ";

       String PRODUCT_BIDS_RETRIEVE="PRODUCT BIDS RETRIEVED";

       String INVALID_SELLER_REQUEST="INVALID SELLER REQUEST";

       String INVALID_PRODUCT_REQUEST="INVALID PRODUCT REQUEST";

       String INVALID_PRODUCT_CATEGORY="INVALID PRODUCT CATEGORY";

       String INVALID_PRODUCT_STARTING_PRICE="INVALID PRODUCT STARTING PRICE";

       String INVALID_PRODUCT_NAME="INVALID PRODUCT NAME";

       String INVALID_SELLER_FIRST_NAME="INVALID SELLER FIRST NAME";

       String INVALID_SELLER_LAST_NAME="INVALID SELLER LAST NAME";

       String INVALID_SELLER_PRODUCT_BID_ENDATE_NULL="INVALID SELLER BID END DATE NULL";

       String INVALID_SELLER_PRODUCT_BID_ENDATE="INVALID SELLER PRODUCT BID END DATE IS NOT FUTURE DATE";

       String INVALID_SELLER_PRODUCT_BID_ENDATE_FMT="INVALID SELLER PRODUCT BID END DATE FORMAT";

       String INVALID_SELLER_PHONE_NUMBER="INVALID SELLER PHONE NUMBER";

       String INVALID_SELLER_EMAIL="INVALID SELLER EMAIL";

       //-----------------------------------

       String INVALID_BUYER_REQUEST="INVALID BUYER REQUEST";

       String INVALID_BUYER_FIRST_NAME="INVALID BUYER FIRST NAME";

       String INVALID_BUYER_LAST_NAME="INVALID BUYER LAST NAME";

       String INVALID_BUYER_PHONE_NUMBER="INVALID BUYER PHONE NUMBER";

       String INVALID_BUYER_EMAIL="INVALID BUYER EMAIL";

       String INVALID_BID_AMT="INVALID BID AMT";

       String NOT_UPDATE_BUYER_DETAILS="NOT UPDATED BUYER DETAILS";

       String UPDATED_BUYER_DETAILS="UPDATED BUYER DETAILS";

       String INVALID_BUYER_DETAILS="INVALID BUYER DETAILS";

       String INVALID_PRODUCT_BID="INVALID PRODUCT BID";

       String INVALID_PRODUCT_BID_ID="INVALID PRODUCT ID";

       String INVALID_PRODUCT_BID_DATE="INVALID PRODUCT BID DATE";

       String INVALID_PRODUCT_BID_TWICE="BUYER CANT BID PRODUCT AGAIN";

       String INVALID_PRODUCT_FOR_DELETION="PRODUCT DO NOT EXIST";

       String INVALID_PRODUCT="PRODUCT DO NOT EXIST";

       String PRODUCT_AVAILABLE_BID="PRODUCT AVAILABLE FOR BID";

       String INVALID_PRODUCT_BID_CURRENT_DATE="PRODUCT CANT BE DELETED AS IT HAVE BIDS OR CURRENT DATE IS AFTER BID END DATE";

                                   



}